name = "PendulumDemo"
uuid = "cd4e131a-7f46-4e56-87f1-25aad45a5eeb"
authors = ["zszalan98 <zszalan98@gmail.com>"]
version = "0.1.0"

[deps]
GenieFramework = "a59fdf5c-6bf0-4f5d-949c-a137c9e2f353"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[compat]
GenieFramework = "~2.4"
ModelingToolkit = "~9.45"
OrdinaryDiffEq = "~6.89"
julia = "~1.10"
